export const ImmediateActions = [
  "Nutrition Guidance",
  "Suggestions",
  "Actions Now",
  "Symptom Relief",
  "Vital Monitoring",
  "Generic Diagnosis",
  "Prevent Severe",
  "Exercise Plans",
  "Advice",
  "Medication Tracking",
  "Chat",
  "Emergency Contacts",
  "Tư vấn dinh dưỡng",
  "Lời khuyên",
  "Hành động ngay",
  "Giảm triệu chứng",
  "Giám sát tình trạng",
  "Ngăn chặn nghiêm trọng",
  "Chẩn đoán",
  "Liên hệ khẩn cấp",
  "Kế hoạch tập thể dục",
  "Lời khuyên",
  "Theo dõi thuốc",
  "Trò chuyện",
];

export const LongTermActions = [
  "Health Tracking",
  "Visualization",
  "Health Management",
  "Improved Life",
  "Critical Illness",
  "Goal Setting",
  "Check-up Reminders",
  "Education Resources",
];
