version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "npm run start"
    container_name: web-client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      OPENAI_API_KEY:
    volumes:
      - app:/app
    networks:
      - client.local

volumes:
  app:

networks:
  client.local:
