version: '3.8'

services:
  jenkins:
    build:
      context: ./
      dockerfile: devops/Dockerfile
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins-local
    volumes:
      - jenkins_data:/var/jenkins_home
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt
    env_file:
      - devops/infrastructure/properties.env
      - devops/infrastructure/local.env
    networks:
      - client.local

  sonarqube:
    image: sonarqube:9.9.0-community
    container_name: sonarqube-local
    ports:
      - "9000:9000"
    networks:
      - client.local
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  nginx:
    image: nginx:latest
    container_name: nginx-local
    ports:
      - "80:80"
    volumes:
      - ./devops/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jenkins
      - sonarqube
    networks:
      - client.local

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "npm run start"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - app:/app
    networks:
      - client.local

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  jenkins_data:
  app:

networks:
  client.local:
